### ISSUE TITLE
Tables are not being created

### ISSUE THREAD

**Issue by magrojd** [authsio/core#11]
While setting up the backend component on my machine, I noticed that sql tables are not being created on my postgresql database, I have confirmed that my database credentials are correct. 

I have `DATABASE_FORCE_SYNC=yes` enabled. Am I missing something?

**Comment by hkd987** [comment]
Since we are not database schema set, I’ve yet to add the sequalize.initialized method right after the checking of the db auth. 

I’ve done this for a few reasons but mainly bc I don’t want to starting writing migrations yet. After DB version 1 is set then we will start creating tables.
