### ISSUE TITLE
The Best Frontend Framework For Authsio Discussion  

### ISSUE THREAD

**Issue by hkd987** [authsio/core#19]
As a project we want to choose the best frontend frame work that will not only support long term success but also attract the right mix of developers and contributions. Currently we have a few contenders and want to get open feedback from the community as to what they feel will work for us. 

- Vue 3
- React
- Svelte
- Preact

Taking the above options give us some pros and cons of each framework and what you would choose if you were starting a new project today.

**Comment by evanyang1** [comment]
I think React is the most popular, with the vast majority or at least many startups (and maybe large tech companies) use React. React has the largest community I believe.

**Comment by cedpoilly** [comment]
(I come in peace) 

Preact I believe is light and fast, yet might lack some features for a project of this size.

React is definitely the most popular, yet I feel there are different ways of doing things. And is there a recommended standard? Asking as I know little about React.

Svelte is more complete than Preact, especially with its ecosystem. Yet wouldn't it still lack some features for a complex codebase?

I work mostly with Vue (so DISCLAIMER I guess 🤷‍♂️) and Vue 3 with the updates, including the composition API offer enough modularity IMHO. The feature set covers what is needed for a project this size. The plus it can have over React is that Vue has recommended standards & modules developed by its core team. This might help with contributions being more uniform and aligned with what would be set by the Authsio core team.

**Comment by evanyang1** [comment]
In my opinion, React would attract the most developers. Otherwise it doesn't matter what tech stack we use, so long as it's easy to use and gets the job done. So Vue 3 would be a good idea as well.

For a project of this size it's better to use some suitable for companies, so Preact is probably not a good idea. I would narrow it down to React or Vue3. I've never used Angular, but I heard it's a headache to use.

**Comment by h3ndry** [comment]
Svelte.
Anyone with knowledge of javascript can easily read the code and understand it. 
Development speed. You don't need a powerful machine to work with.
The community is welcoming

but is still New. so

**Comment by bherbruck** [comment]
React has the biggest ecosystem but many React developers who have dabbled in Svelte will tell you they'd rather use Svelte for new projects (so long as you don't need a mature component library).

**Comment by evanyang1** [comment]
OK i'm down to use Svelte. Just done some web surfing and Svelte looks like something I can pick up very quickly.

**Comment by hkd987** [comment]
I think it sounds like we will research Svelte! Thanks everyone for participating.
