### ISSUE TITLE
frontend - Design & Build Static Frontend

### ISSUE THREAD

**Issue by hkd987** [authsio/core#4]
The frontend is how most of our users will interact with the application some of the key requirements are as follows.

This depends on at the least #2 being done. so to allow the Login & Registration pages to be completed.

- Login & Registration page uses the iframe design, if iframe changes are needed to support use cases lets talk
- Dashboard that shows current projects
- Clicking on projects will show users in that project
- Allow exporting of projects users
- Should allow creation of new projects
- Dashboard should have a settings option 
- Settings should allow payment (if env is set)
- Settings should allow account deletion and clearing of all users

I think this is a solid starting point to get started on design, 

In my mind this is very basic left menu and main screen 

The left menu has Projects, and Settings

IF YOU PLAN TO CONTRIBUTE OR WORK ON THIS ISSUE, LETS CHAT FIRST TO SYNC UP.

https://app.bountysource.com/issues/104978541-frontend-design-build-static-frontend

**Comment by hkd987** [comment]
@cedpoily Do you think you have time to break this down into smaller sections of work. Ive got some ideas how we can get this out quicker.

**Comment by evanyang1** [comment]
Any specifications on css libraries or generally, how this should look?

**Comment by hkd987** [comment]
For CSS we will keep with what we have done for the iframe and use tailwind css.

**Comment by evanyang1** [comment]
If we're going to setting on Svelte, let me know what we can work on: perhaps split the task into several issues.

**Comment by dmitriy-korotayev** [comment]
Good morning/day/evening/night.

In case there'll be needed any help with putting design to work, hit me up. 
Found a bounty on bountysource.com and would be happy to take part in doing frontend work.
While am not a designer myself, in short, had 10 years of frontend experience, willing to expand it in open-source too.

Wishing all the backers @hkd987 a productive week beforehand.
In any case, hope your app will have its' success and smooth dev progress ^^.
