### ISSUE TITLE
frontend - Connect to backend api and implement business logic

### ISSUE THREAD

**Issue by hkd987** [authsio/core#5]
Depends on #1 

TODO: Write this ticket. 

IF YOU PLAN TO CONTRIBUTE OR WORK ON THIS ISSUE, LETS CHAT FIRST TO SYNC UP.

**Comment by cedpoilly** [comment]
@hkd987 As we have the back-end working, I will work on connecting the front-end to it. The UI will be minimal and temporary, as the main focus will be on the network calls.

**Comment by cedpoilly** [comment]
@hkd987 can we close this issue?
The PR is merged https://github.com/authsio/core/pull/24
