### ISSUE TITLE
documentation - Project readme.md

### ISSUE THREAD

**Issue by hkd987** [authsio/core#9]
Lets get the base readme in the top level of the project figured out...

- Backend Details
- iframe Details
- Frontend Details
- Project Plan
- Contributors List
- Companies Using Software List

THIS IS LOW PRIORITY BUT WILL BE A NICE TO HAVE, IF YOUR INTERESTED LET'S CHAT

**Comment by HaedrichHC** [comment]
Hi, I would like to help you with the project readme.

**Comment by hkd987** [comment]
Sure, we do not have a huge amount to document right now but I would love to see what you come up with im pretty open to letting you work the issue!

A really good outline would be amazing!!!

**Comment by HaedrichHC** [comment]
Hi Lundin,

for the readme, i need more information about the following topics:  

- Backend Details:
   Can you give me here a descreption or graphic or something like that?
- iframe Details
   Can you give me here a descreption or graphic or something like that?
- Frontend Details
  Can you give me here a descreption or graphic or something like that?
- Project Plan
  Do you have a project plan?
- Contributors List
   Are there already Contributors to this project?  If yes, which ones?
- Companies Using Software List:
   Are there already companies that use authsio? If yes, which ones?

Further suggestions for the readme:

- Contributing:
  a short description, how can people contribut to the project
- License:
  information about the license

My first draft:
![authsio](https://user-images.githubusercontent.com/89077207/150975830-7756ee01-fb28-4d80-89b1-bf383473b0a3.JPG)

**Comment by hkd987** [comment]
### Project Plan
An open source identity & access management solution that will serve as a multi tenant drop in access management solution. There are many other access management tools on the market but nothing that is multi tenant by design and can be self hosted. Today with privacy and security concerns of your users in mind you need an IAM that separates your concerns. With that in mind, our current project plan is to get a MVP out the door in the next couple months. 

### Backend Details:
 - Planning in process but we will want to document how to use the backend and how to set it up once it's ready
### iframe Details
 - Planning in process
### Frontend Details
 - Planning in process
### Contributors List
 - This should just read from the Github contributions? Is that possible?
### Companies Using Software List:
 - None yet, check back soon.

### Contributing:
 - Can you find an example from some other public repos?
### License:
 - a link is fine here...

**Comment by hkd987** [comment]
Just FYI, Ive added some developer setup sections into the readme, so please make sure to resolve any conflicts before you put up a PR.

**Comment by HaedrichHC** [comment]
thank you for the information.

- Contributing:
  the most projects have a seperated Contribution document like this:
   - [raspberrypi-pico-examples](https://github.com/raspberrypi/pico-examples/blob/master/CONTRIBUTING.md)
   - [vscode](https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md)
   - [flask](https://github.com/pallets/flask/blob/main/CONTRIBUTING.rst)
   or projects have no contribution guideline or something like that

- Contributor list:
  the most projects have no contributor list in the readme. I don'think that is possible. Usually the contributors list is on the right 
  side of the respository like this:
  
![image](https://user-images.githubusercontent.com/89077207/151189330-0291a64c-4149-4339-8894-3f88323cb972.png)

**Comment by hkd987** [comment]
No worries what ever we can make work is perfect!

**Comment by hkd987** [comment]
Closing for now https://github.com/authsio/core/pull/16
